services:
  auth-service:
    build:
      context: ./auth_services
      dockerfile: Dockerfile
    container_name: auth-service
    networks:
      - cb
    ports:
      - "9000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/career_booklet
      - SECRET_KEY=c0d91c42f8aac2ab9103fc265ee21ecaa995f78cdaf0e08044f3ccbe8ece679d
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - REFRESH_TOKEN_EXPIRE_MINUTES=1440

  profile_mgmt_service:
    build:
      context: ./profile_management_services
      dockerfile: Dockerfile
    ports:
      - "9001:8000"
    container_name: profile-service
    networks:
      - cb
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/career_booklet
      - PROFILE_SERVICE=http://127.0.0.1:8000

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    networks:
      - cb
    ports:
      - "9002:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/career_booklet
      - AUTH_SERVICE=http://auth-service:8000
      - PROFILE_SERVICE=http://profile-service:8000
      - ALLOWED_ORIGINS=*
      - BLOGS_SERVICES=http://blog-service:8000

  blog_service:
    build:
      context: ./Blogs
      dockerfile: Dockerfile
    container_name: blog-service
    networks:
      - cb
    ports:
      - "9003:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/career_booklet
      - PROFILE_SERVICE=http://profile-service:8000

networks:
  cb:
    external: true
