version: "3.8"

services:
  service1:
    build:
      context: ./auth_services
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/career_booklet
    depends_on:
      - db
    command: ["sh", "-c", "until nc -z db 5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload"]

  service2:
    build:
      context: ./profile_management_services
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/career_booklet
    depends_on:
      - db
    command: ["sh", "-c", "until nc -z db 5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 9001 --reload"]

  service3:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/career_booklet
    depends_on:
      - db
    command: ["sh", "-c", "until nc -z db 5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 9002 --reload"]

  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: career_booklet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
