"""create user table

Revision ID: 81d339095667
Revises: 3b4cad24bd75
Create Date: 2024-12-30 00:44:34.848110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d339095667'
down_revision: Union[str, None] = '3b4cad24bd75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about_user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('about_user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('skills', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user_skills', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user_skills', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skills', 'updated_at')
    op.drop_column('user_skills', 'created_at')
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'created_at')
    op.drop_column('about_user', 'updated_at')
    op.drop_column('about_user', 'created_at')
    # ### end Alembic commands ###
