"""modified table

Revision ID: cd57bee415dd
Revises: acf74c034c6f
Create Date: 2024-12-31 11:06:57.290750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd57bee415dd'
down_revision: Union[str, None] = 'acf74c034c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_skills', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'user_skills', 'skills', ['skill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_skills', type_='foreignkey')
    op.alter_column('user_skills', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
